### ISSUE TITLE
missing dependency 

### ISSUE THREAD

**Issue by enjoylife** [taskworld/react-overlay-popup#1]
the npm module "invariant" is missing from package.json.

**Comment by dtinth** [comment]
Wow, sorry, I did not notice your comment.

Will fix it when I have more time.

**Comment by That-David-Guy** [comment]
+1

**Comment by dtinth** [comment]
Thanks for the reminder. I’m migrating this project to use `nwb`. See #3.

**Comment by dtinth** [comment]
This should be fixed as of v4.0.0 :smile:
